SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `tiankong_acm`.`contest` DROP COLUMN `duration` , ADD COLUMN `duration` BIGINT(20) NULL DEFAULT 18000  AFTER `state` ;

ALTER TABLE `tiankong_acm`.`problem` ADD COLUMN `contest` LONGTEXT NULL DEFAULT NULL  AFTER `AC` ;

ALTER TABLE `tiankong_acm`.`contest_update_problem` 
ADD INDEX `fk_contest_update_problem_contest1_idx` (`contest_id` ASC) 
, DROP INDEX `fk_contest_update_problem_contest1_idx` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
